
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  mvc:
    view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
    format:
      date: iso
  jpa:
    properties.hibernate:
      hbm2ddl.auto: update
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      show_sql: true
      format_sql: true
    open-in-view: false

